name: Test
on:
  push:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build, Unit test, Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/exe/calc/calc

      - name: Install Doxygen
        run: sudo apt install doxygen && doxygen --version

      - name: Install Graphviz
        run: sudo apt install graphviz

      - name: Create documentation     
        run:  cd doc && doxygen
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: build/doc/html/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  runs:
    name: Download, Run
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x calc && ./calc