name: Test
on:
  push:
jobs:
  build:
    name: Build, Unit test, Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/exe/calc/calc

  runs:
    name: Upload and Run
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x calc && ./calc