name: basic
on: [push]
jobs:
  build:
    name: MyVegaProject
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - uses: actions/checkout@v4

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0

  run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 2 7